-- ===========================================================================
-- LoveLi Care — full schema for project tziwrqpvnncddbvlclyg
-- "LoveLiCare Medspa and Wellness Services"
--
-- HOW TO RUN
--   Supabase Dashboard -> SQL Editor -> New query -> paste this whole file -> Run
--   https://supabase.com/dashboard/project/tziwrqpvnncddbvlclyg/sql/new
--
-- Safe to run on an empty project. Every statement is idempotent
-- (create table if not exists / create index if not exists / on conflict do
-- nothing), so re-running it will not duplicate or destroy anything.
--
-- Generated by concatenating supabase/migrations/0001..0003 in order.
-- ===========================================================================



-- =========================================================================
-- 0001 — form intake (contact_inquiries, newsletter_subscribers)
-- =========================================================================

-- LoveLi Care Med Spa — form intake tables
-- Each form field lands in its own labeled column so inquiries are queryable,
-- not buried in an email body.
--
-- Writes happen server-side with the publishable key and insert-only RLS.
-- Public roles may submit forms but cannot read, update, or delete rows.

-- ── Contact / consultation inquiries (the main contact form) ────────────────
create table if not exists public.contact_inquiries (
  id          uuid primary key default gen_random_uuid(),
  created_at  timestamptz not null default now(),

  -- Labeled form sections, 1:1 with the fields on the contact form
  name        text,                 -- "Your Name"
  email       text not null,        -- "Email *"
  phone       text,                 -- "Phone"
  service     text,                 -- "Service Interest" (dropdown)
  message     text,                 -- "Message"

  -- Triage / provenance
  status      text not null default 'new'
              check (status in ('new', 'contacted', 'booked', 'closed', 'spam')),
  source      text not null default 'website_contact_form',
  page_url    text,
  user_agent  text,
  notes       text                  -- staff-only follow-up notes
);

comment on table  public.contact_inquiries is 'Submissions from the LoveLi Care website contact form.';
comment on column public.contact_inquiries.service is 'Selected "Service Interest" option, e.g. Medical Aesthetics (Botox / Fillers).';
comment on column public.contact_inquiries.status  is 'Follow-up state, managed by staff. Defaults to new.';

create index if not exists contact_inquiries_created_at_idx on public.contact_inquiries (created_at desc);
create index if not exists contact_inquiries_status_idx     on public.contact_inquiries (status);
create index if not exists contact_inquiries_email_idx      on public.contact_inquiries (email);

alter table public.contact_inquiries enable row level security;

-- ── Newsletter / wellness community subscribers ─────────────────────────────
create table if not exists public.newsletter_subscribers (
  id             uuid primary key default gen_random_uuid(),
  created_at     timestamptz not null default now(),

  email          text not null,
  status         text not null default 'subscribed'
                 check (status in ('subscribed', 'unsubscribed')),
  source         text not null default 'website_subscribe_form',
  page_url       text,
  user_agent     text,
  unsubscribed_at timestamptz
);

comment on table public.newsletter_subscribers is 'Email signups from the LoveLi Care online store subscribe form.';

-- One row per address, case-insensitive. Lets the API treat a repeat signup as
-- success instead of surfacing an error to the visitor.
create unique index if not exists newsletter_subscribers_email_key
  on public.newsletter_subscribers (lower(email));

create index if not exists newsletter_subscribers_created_at_idx
  on public.newsletter_subscribers (created_at desc);

alter table public.newsletter_subscribers enable row level security;

-- ── Insert-only access for the public site ─────────────────────────────────
-- The site may add a submission and nothing else. With no SELECT/UPDATE/DELETE
-- policy, those operations are denied for anon and authenticated, so a leaked
-- publishable key cannot read anyone's contact details. Staff read the rows in
-- the Supabase dashboard, which authenticates separately.
drop policy if exists "public can submit an inquiry" on public.contact_inquiries;
create policy "public can submit an inquiry"
  on public.contact_inquiries for insert to anon, authenticated with check (true);

drop policy if exists "public can subscribe" on public.newsletter_subscribers;
create policy "public can subscribe"
  on public.newsletter_subscribers for insert to anon, authenticated with check (true);


-- =========================================================================
-- 0002 — project notes (internal docs sync, deny-by-default RLS)
-- =========================================================================

-- LoveLi Care — project notes / session memory
--
-- Durable home for the markdown planning docs in docs/, so a new Claude session
-- (or Obsidian, or a future dashboard) can read project state without the repo.
--
-- SCOPE: internal project documentation ONLY. Plans, decisions, handoffs.
-- This table is NOT for client data and NOT for protected health information.
-- LoveLi Care's stack is deliberately out of HIPAA scope — Supabase will only
-- sign a BAA on Team ($599/mo) + HIPAA add-on ($350/mo) = $949/mo, against a
-- $433/mo budget. See docs/BUDGET.md §1. Clinical intake routes through Vagaro.
--
-- RLS: deny-by-default. NO anon or authenticated policy is created, so the
-- publishable key cannot read or write this table at all. Sync runs server-side
-- with the service-role key, which bypasses RLS. That is the intent: these are
-- internal notes and must never be reachable from a browser.

create table if not exists public.project_notes (
  id           uuid primary key default gen_random_uuid(),

  -- Identity. slug is the stable key the sync upserts on; it comes from the
  -- markdown frontmatter, falling back to the filename.
  slug         text not null unique,
  title        text not null,
  project      text not null default 'lovelicare',

  -- Classification, mirroring the Obsidian frontmatter 1:1 so the same file
  -- round-trips between vault, repo and database without transformation.
  type         text not null default 'note'
               check (type in ('plan','handoff','decision','reference','note','brief')),
  phase        int,
  status       text not null default 'draft'
               check (status in ('draft','planned','in_progress','blocked','complete','superseded')),
  tags         text[] not null default '{}',

  -- Content
  body_md      text not null,                  -- the markdown body, frontmatter stripped
  frontmatter  jsonb not null default '{}',    -- full frontmatter, so nothing is lost
  source_path  text,                           -- e.g. docs/HERO-VIDEO-PLAN.md

  -- Idempotent sync: unchanged files are skipped instead of rewritten.
  content_hash text not null,

  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

comment on table  public.project_notes is
  'Internal LoveLi Care planning docs synced from docs/*.md. No client data, no PHI.';
comment on column public.project_notes.slug is
  'Stable upsert key from frontmatter `slug`, else the filename.';
comment on column public.project_notes.content_hash is
  'sha256 of the raw file. Lets the sync skip unchanged notes.';
comment on column public.project_notes.frontmatter is
  'Complete frontmatter as JSON so Obsidian-only fields survive the round trip.';

create index if not exists project_notes_project_idx on public.project_notes (project);
create index if not exists project_notes_type_idx    on public.project_notes (type);
create index if not exists project_notes_status_idx  on public.project_notes (status);
create index if not exists project_notes_updated_idx on public.project_notes (updated_at desc);
create index if not exists project_notes_tags_idx    on public.project_notes using gin (tags);

-- keep updated_at honest
create or replace function public.touch_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end $$;

drop trigger if exists project_notes_touch on public.project_notes;
create trigger project_notes_touch
  before update on public.project_notes
  for each row execute function public.touch_updated_at();

-- Deny by default. No policies granted to anon/authenticated on purpose.
alter table public.project_notes enable row level security;


-- =========================================================================
-- 0003 — injectable & IV inventory (9 items from vial photos, qty 10)
-- =========================================================================

-- LoveLi Care Med Spa — Injectable / IV inventory
--
-- SOURCE OF TRUTH: every row below was transcribed from a photograph of the
-- physical vial in ~/Desktop/lovelicare-raw-phootage. Nothing here is invented.
-- Where a label was partially obscured in the photo the column is left NULL
-- rather than guessed — see `label_verified`.
--
-- This is PRODUCT inventory, not patient data. No PHI. Safe for the ops tier.
--
--   Photo evidence per row is recorded in `source_image` so any number on the
--   dashboard can be traced back to the picture it came from.

-- ── Catalog ────────────────────────────────────────────────────────────────
create table if not exists public.inventory_items (
  id              uuid primary key default gen_random_uuid(),
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),

  -- Identity, exactly as printed on the vial
  name            text not null,              -- "GLUTATHIONE INJECTION PRESERVATIVE FREE"
  common_name     text,                       -- "Glutathione"
  active_ingredients text,                    -- "Methionine / Inositol / Choline Chloride"
  strength        text,                       -- "200 mg/mL"
  volume_ml       numeric(6,2),               -- 30.00
  ndc             text,                       -- "72827-2402-1"
  manufacturer    text,                       -- "Empower Pharmacy"
  vial_type       text,                       -- "Sterile Single-Dose" | "Multiple Dose"
  route           text,                       -- "IV" | "IM" | "IM or IV" | "IM or SubQ"
  rx_only         boolean not null default true,
  compounded      boolean not null default false,

  -- Merchandising
  category        text not null
                  check (category in ('iv_therapy','im_injection','lipotropic',
                                      'vitamin','mineral','antioxidant','other')),
  benefits        text[],                     -- from the clinic's own chalkboard

  -- Stock
  quantity        integer not null default 0 check (quantity >= 0),
  reorder_at      integer not null default 10,
  unit            text not null default 'vial',

  -- Provenance
  source_image    text,                       -- the photo this row was read from
  label_verified  boolean not null default false,
  notes           text
);

comment on table public.inventory_items is
  'Injectable and IV product catalog, transcribed from vial photographs. No PHI.';
comment on column public.inventory_items.reorder_at is
  'Base count. At or below this, the item is flagged low on the dashboard.';
comment on column public.inventory_items.source_image is
  'Filename in lovelicare-raw-phootage that this row was read from.';

create index if not exists inventory_items_category_idx on public.inventory_items (category);
create index if not exists inventory_items_quantity_idx on public.inventory_items (quantity);
create unique index if not exists inventory_items_name_strength_key
  on public.inventory_items (lower(name), coalesce(strength, ''));

-- ── Movement log — every change to quantity, append-only ───────────────────
-- Without this a stock number is just an assertion. With it, the dashboard can
-- show a count that is the sum of its movements, which is the honesty rule
-- applied to inventory.
create table if not exists public.inventory_movements (
  id           uuid primary key default gen_random_uuid(),
  created_at   timestamptz not null default now(),
  item_id      uuid not null references public.inventory_items(id) on delete cascade,
  delta        integer not null,              -- -1 used, +10 restocked
  reason       text not null
               check (reason in ('received','administered','wasted','expired',
                                 'adjustment','initial_count')),
  staff_label  text,                          -- "Libra R." — never a full client name
  note         text
);

create index if not exists inventory_movements_item_idx
  on public.inventory_movements (item_id, created_at desc);

comment on table public.inventory_movements is
  'Append-only stock ledger. Never records who a dose was given to — no PHI.';

-- ── RLS ────────────────────────────────────────────────────────────────────
-- Deny by default. No anon or authenticated policy is created, so inventory is
-- unreadable from a browser. The dashboard reads it server-side with the
-- service-role key, exactly like contact_inquiries.
alter table public.inventory_items     enable row level security;
alter table public.inventory_movements enable row level security;

-- ── Seed: base count 10, every item stocked at 10 ──────────────────────────
insert into public.inventory_items
  (name, common_name, active_ingredients, strength, volume_ml, ndc, manufacturer,
   vial_type, route, rx_only, compounded, category, benefits,
   quantity, reorder_at, source_image, label_verified)
values
  ('GLUTATHIONE INJECTION PRESERVATIVE FREE', 'Glutathione', 'Glutathione',
   '200 mg/mL', 30, '72827-2402-1', 'Empower Pharmacy',
   'Sterile Single-Dose', 'IV', true, true, 'antioxidant',
   array['Skin brightening','Detoxification','Antioxidant support'],
   10, 10, 'gluthathione-injection-and-biotin.png', true),

  ('BIOTIN SOLUTION FOR INJECTION', 'Biotin', 'Biotin',
   '10 mg/mL', 30, '72833-589-30', 'ASP Cares',
   'Multiple Dose', 'IM or IV', true, false, 'vitamin',
   array['Strong hair & nails','Skin health'],
   10, 10, 'gluthathione-injection-and-biotin.png', true),

  ('LIPO INJECTION', 'Lipotropic', 'Methionine / Inositol / Choline Chloride',
   '25 / 50 / 50 mg/mL', 30, '72827-2415-1', 'Empower Pharmacy',
   'Sterile Multiple-Dose', 'IM', true, true, 'lipotropic',
   array['Burn fat','Boost metabolism'],
   10, 10, 'libo-injection-and-libo-b-injection.png', true),

  ('LIPO-B INJECTION', 'Lipotropic B',
   'Methionine / Inositol / Choline Chloride / Cyanocobalamin',
   '25 / 50 / 50 / 1 mg/mL', 30, '72827-2419-1', 'Empower Pharmacy',
   'Sterile Multiple-Dose', 'IM', true, true, 'lipotropic',
   array['Burn fat','Boost metabolism','Energy'],
   10, 10, 'libo-injection-and-libo-b-injection.png', true),

  ('TAURINE INJECTION', 'Taurine', 'Taurine',
   '50 mg/mL', 30, null, 'Empower Pharmacy',
   'Sterile Multiple-Dose', 'IM', true, true, 'im_injection',
   array['Energy','Metabolic support'],
   10, 10, 'taurine-pryridozine--hcl-b6.JPG', true),

  ('PYRIDOXINE HCL (B6) INJECTION', 'Vitamin B6', 'Pyridoxine Hydrochloride',
   '100 mg/mL', 30, null, 'Empower Pharmacy',
   'Sterile Multiple-Dose', 'IM', true, true, 'vitamin',
   array['Energy','Metabolism','Mood support'],
   10, 10, 'taurine-pryridozine--hcl-b6.JPG', true),

  ('COENZYME Q-10 (UBIDECARENONE) INJECTION', 'CoQ10', 'Ubidecarenone',
   '20 mg/mL', 10, null, 'Empower Pharmacy',
   'Sterile Multiple Dose', 'IM or SubQ', true, true, 'antioxidant',
   array['Cellular energy','Antioxidant support','Heart health'],
   10, 10, 'coenzyme-q-10.png', true),

  ('VITAMIN D3 INJECTION', 'Vitamin D3', 'Cholecalciferol',
   '50,000 IU/mL', 30, '73198-0075', 'Olympia Compounding Pharmacy',
   'Multiple Dose', 'IM', true, true, 'vitamin',
   array['Immune support','Bone health','Mood support'],
   10, 10, 'vitamin-d3.JPG', true),

  ('ZINC CHLORIDE INJECTION', 'Zinc', 'Zinc Chloride',
   '0.5 mg/mL', 30, null, 'Olympia Pharmaceuticals',
   'Multi-Dose', 'IV', true, true, 'mineral',
   array['Immune support','Skin healing'],
   10, 10, 'zinc-chloride.png', true)
on conflict do nothing;

-- Opening count, so every quantity above is backed by a ledger row.
insert into public.inventory_movements (item_id, delta, reason, staff_label, note)
select id, quantity, 'initial_count', 'Libra R.',
       'Opening count from vial photographs, ' || coalesce(source_image, 'unknown')
from public.inventory_items
where not exists (
  select 1 from public.inventory_movements m
  where m.item_id = public.inventory_items.id and m.reason = 'initial_count'
);
